export const CHANGE_ROLESDATA = 'CHANGE_ROLESDATA';
export const CHANGE_ROLESDATA_SUCCESS = 'CHANGE_ROLESDATA_SUCCESS';
export const CHANGE_ROLESDATA_FAIL = 'CHANGE_ROLESDATA_FAIL';

export const GET_ROLES = 'GET_ROLES';
export const GET_ROLES_SUCCESS = 'GET_ROLES_SUCCESS';
export const GET_ROLES_FAIL = 'GET_ROLES_FAIL';

export const SAVE_ROLE = 'SAVE_ROLE';
export const SAVE_ROLE_SUCCESS = 'SAVE_ROLE_SUCCESS';
export const SAVE_ROLE_FAIL = 'SAVE_ROLE_FAIL';

export const REMOVE_ROLE = 'REMOVE_ROLE';
export const REMOVE_ROLE_SUCCESS = 'REMOVE_ROLE_SUCCESS';
export const REMOVE_ROLE_FAIL = 'REMOVE_ROLE_FAIL';

export const UPDATE_ROLE = 'UPDATE_ROLE';
export const UPDATE_ROLE_SUCCESS = 'UPDATE_ROLE_SUCCESS';
export const UPDATE_ROLE_FAIL = 'UPDATE_ROLE_FAIL';

export const UPDATE_ROLES_REDUCER_SUCCESS = 'UPDATE_ROLES_REDUCER_SUCCESS';

export const ROLE_REFLINK_MASS_CREATE = 'ROLE_REFLINK_MASS_CREATE';
export const ROLE_REFLINK_MASS_CREATE_SUCCESS =
'ROLE_REFLINK_MASS_CREATE_SUCCESS';
export const ROLE_REFLINK_MASS_CREATE_FAIL = 'ROLE_REFLINK_MASS_CREATE_FAIL';

export const ROLE_REFITEMLINK_MASS_CREATE = 'ROLE_REFITEMLINK_MASS_CREATE';
export const ROLE_REFITEMLINK_MASS_CREATE_SUCCESS =
'ROLE_REFITEMLINK_MASS_CREATE_SUCCESS';
export const ROLE_REFITEMLINK_MASS_CREATE_FAIL =
'ROLE_REFITEMLINK_MASS_CREATE_FAIL';

export const ROLE_REFLINK_MASS_DELETE = 'ROLE_REFLINK_MASS_DELETE';
export const ROLE_REFLINK_MASS_DELETE_SUCCESS =
'ROLE_REFLINK_MASS_DELETE_SUCCESS';
export const ROLE_REFLINK_MASS_DELETE_FAIL = 'ROLE_REFLINK_MASS_DELETE_FAIL';

export const ROLE_REFITEMLINK_MASS_DELETE = 'ROLE_REFITEMLINK_MASS_DELETE';
export const ROLE_REFITEMLINK_MASS_DELETE_SUCCESS =
'ROLE_REFITEMLINK_MASS_DELETE_SUCCESS';
export const ROLE_REFITEMLINK_MASS_DELETE_FAIL =
'ROLE_REFITEMLINK_MASS_DELETE_FAIL';

export const GET_ROLE_REFLINK = 'GET_ROLE_REFLINK';
export const GET_ROLE_REFLINK_SUCCESS = 'GET_ROLE_REFLINK_SUCCESS';
export const GET_ROLE_REFLINK_FAIL = 'GET_ROLE_REFLINK_FAIL';

export const GET_ROLE_REFITEMLINK = 'GET_ROLE_REFITEMLINK';
export const GET_ROLE_REFITEMLINK_SUCCESS = 'GET_ROLE_REFITEMLINK_SUCCESS';
export const GET_ROLE_REFITEMLINK_FAIL = 'GET_ROLE_REFITEMLINK_FAIL';

