export const GET_REFERENCES = 'GET_REFERENCES';
export const GET_REFERENCES_SUCCESS = 'GET_REFERENCES_SUCCESS';
export const GET_REFERENCES_FAIL = 'GET_REFERENCES_FAIL';

export const GET_APPLICATIONS = 'GET_APPLICATIONS';
export const GET_APPLICATIONS_SUCCESS = 'GET_APPLICATIONS_SUCCESS';
export const GET_APPLICATIONS_FAIL = 'GET_APPLICATIONS_FAIL';

export const GET_QUERYSUGGEST = 'GET_QUERYSUGGEST';
export const GET_QUERYSUGGEST_SUCCESS = 'GET_QUERYSUGGEST_SUCCESS';
export const GET_QUERYSUGGEST_FAIL = 'GET_QUERYSUGGEST_FAIL';

export const GET_REFERENCEITEMS = 'GET_REFERENCEITEMS';
export const GET_REFERENCEITEMS_SUCCESS = 'GET_REFERENCEITEMS_SUCCESS';
export const GET_REFERENCEITEMS_FAIL = 'GET_REFERENCEITEMS_FAIL';

export const SAVE_REFERENCEITEM = 'SAVE_REFERENCEITEM';
export const SAVE_REFERENCEITEM_SUCCESS = 'SAVE_REFERENCEITEM_SUCCESS';
export const SAVE_REFERENCEITEM_FAIL = 'SAVE_REFERENCEITEM_FAIL';


export const UPDATE_REFERENCEITEM = 'UPDATE_REFERENCEITEM';
export const UPDATE_REFERENCEITEM_SUCCESS = 'UPDATE_REFERENCEITEM_SUCCESS';
export const UPDATE_REFERENCEITEM_FAIL = 'UPDATE_REFERENCEITEM_FAIL';

export const DELETE_REFERENCEITEMS = 'DELETE_REFERENCEITEMS';
export const DELETE_REFERENCEITEMS_SUCCESS = 'DELETE_REFERENCEITEMS_SUCCESS';
export const DELETE_REFERENCEITEMS_FAIL = 'DELETE_REFERENCEITEMS_FAIL';

export const SAVE_REFERENCE = 'SAVE_REFERENCE';
export const SAVE_REFERENCE_SUCCESS = 'SAVE_REFERENCE_SUCCESS';
export const SAVE_REFERENCE_FAIL = 'SAVE_REFERENCE_FAIL';

export const REMOVE_REFERENCE = 'REMOVE_REFERENCE';
export const REMOVE_REFERENCE_SUCCESS = 'REMOVE_REFERENCE_SUCCESS';
export const REMOVE_REFERENCE_FAIL = 'REMOVE_REFERENCE_FAIL';

export const UPDATE_REFERENCE = 'UPDATE_REFERENCE';
export const UPDATE_REFERENCE_SUCCESS = 'UPDATE_REFERENCE_SUCCESS';
export const UPDATE_REFERENCE_FAIL = 'UPDATE_REFERENCE_FAIL';

export const ADD_REFERENCEITEM_SUCCESS = 'ADD_REFERENCEITEM_SUCCESS';
export const ADD_REFERENCEITEM_FAIL = 'ADD_REFERENCEITEM_FAIL';

export const REMOVE_REFERENCEITEM_SUCCESS = 'REMOVE_REFERENCEITEM_SUCCESS';
export const REMOVE_REFERENCEITEM_FAIL = 'REMOVE_REFERENCEITEM_FAIL';

export const ADD_REFERENCEHEADER_SUCCESS = 'ADD_REFERENCEHEADER_SUCCESS';
export const ADD_REFERENCEHEADER_FAIL = 'ADD_REFERENCEHEADER_FAIL';

export const CLEAR_REFERENCEITEMS_SUCCESS = 'CLEAR_REFERENCEITEMS_SUCCESS';
export const CLEAR_REFERENCEITEMS_FAIL = 'CLEAR_REFERENCEITEMS_FAIL';
